# Generated by Django 5.2 on 2025-06-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedproduct',
            name='actual_product_id',
            field=models.CharField(default='sensor_id_1', max_length=100),
        ),
    ]
